### ISSUE TITLE
Graph SIM Usage

### ISSUE THREAD

**Issue by marcoherbst** [ijunaid8989/edge-commander#9]

**Comment by ijunaid8989** [comment]
Graph has been added for sim usage,
```
xAxis = Datetime
yAxis = (volume_used / allowance * 100)
```

![image](https://user-images.githubusercontent.com/13561999/30901104-fc94b624-a37f-11e7-97e6-74b36223f7e2.png)

**Comment by ijunaid8989** [comment]
its done.
